### ISSUE TITLE
 RuntimeError: Aborted(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -sASSERTIONS for more info

### ISSUE THREAD

**Issue by VasgoTheTotoroo** [supertorpe/lila-stockfish-web-example#1]
Hello !
I'm trying to reproduce your example in my code but I get an error but I get the error `RuntimeError: Aborted(CompileError: wasm validation error: at offset 4: failed to match magic number). Build with -sASSERTIONS for more info`

![image](https://github.com/user-attachments/assets/c7a95af0-6ccc-4adf-8c3e-1605edf8c2d7)

I precise that my application is in vue.js 3

**Comment by supertorpe** [comment]
What version of Vite are you using? It seems like it's serving .wasm files as text/html  instead of application/wasm.
You can try to add this to the server middleware:
```typescript
const serverConfig = (server) => {
  server.middlewares.use((req, res, next) => {
    res.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
    res.setHeader("Cross-Origin-Opener-Policy", "same-origin");
    if (req.url.endsWith(".wasm")) {
      res.setHeader("Content-Type", "application/wasm");
    }
    next();
  });
}
```

**Comment by VasgoTheTotoroo** [comment]
I'm using the 5.3.1 and you have the 5.4.6.
Your fix worked, thank you very much !
